class CfgPatches
{
    class TEST_Custom_Units
    {
        units[] =
        	{
				//TCU Emmeria Militants
				"TCU_EMME_MSL_IND",
				"TCU_EMME_MTL_IND",
				"TCU_EMME_MOF_IND",
				"TCU_EMME_MRM_IND",
				"TCU_EMME_MRMAT_IND",
				"TCU_EMME_MMKM_IND",
				"TCU_EMME_MSNP_IND",
				"TCU_EMME_MMMG_IND",
				"TCU_EMME_MMMGA_IND",
				"TCU_EMME_MUAV_IND",
				"TCU_EMME_MAMMO_IND",
				"TCU_EMME_MEN_IND",
				"TCU_EMME_MMD_IND",
				"TCU_EMME_MAAR_IND",
				"TCU_EMME_MAR_IND",
				"TCU_EMME_MAAT_IND",
				"TCU_EMME_MAT_IND",
				"TCU_EMME_MAAA_IND",
				"TCU_EMME_MAA_IND",
				"TCU_EMME_MHP_IND",
				"TCU_EMME_MFP_IND",
				"TCU_EMME_MAR_MTRA",
				"TCU_EMME_MAR_MLMG",
				"TCU_EMME_MAR_MGMG",
				"TCU_EMME_MAR_TRAN",
				"TCU_EMME_MAR_ARMT",
				"TCU_EMME_MAR_ARMA",
				"TCU_EMME_MAR_LTHC",
				"TCU_EMME_MAR_HVHC",
				"TCU_EMME_MAR_GUSH",
				"TCU_EMME_MAR_JTTR",
				"TCU_EMME_MAR_FCAS",
				"TCU_EMME_MAR_BOAT",
				
				"TCU_EMME_MAR_ammobox",
				"TCU_EMME_MAR_wbox",
				
				//TCU Osea Rangers
				"TCU_OSEA_MSL_BLU",
				"TCU_OSEA_MTL_BLU",
				"TCU_OSEA_MOF_BLU",
				"TCU_OSEA_MRM_BLU",
				"TCU_OSEA_MRMAT_BLU",
				"TCU_OSEA_MMKM_BLU",
				"TCU_OSEA_MSNP_BLU",
				"TCU_OSEA_MMMG_BLU",
				"TCU_OSEA_MMMGA_BLU",
				"TCU_OSEA_MUAV_BLU",
				"TCU_OSEA_MAMMO_BLU",
				"TCU_OSEA_MEN_BLU",
				"TCU_OSEA_MMD_BLU",
				"TCU_OSEA_MAAR_BLU",
				"TCU_OSEA_MAR_BLU",
				"TCU_OSEA_MAAT_BLU",
				"TCU_OSEA_MAT_BLU",
				"TCU_OSEA_MAAA_BLU",
				"TCU_OSEA_MAA_BLU",
				"TCU_OSEA_MHP_BLU",
				"TCU_OSEA_MFP_BLU",
				"TCU_OSEA_MAR_MTRA",
				"TCU_OSEA_MAR_MLMG",
				"TCU_OSEA_MAR_MGMG",
				"TCU_OSEA_MAR_TRAN",
				"TCU_OSEA_MAR_ARMT",
				"TCU_OSEA_MAR_ARMA",
				"TCU_OSEA_MAR_LTHC",
				"TCU_OSEA_MAR_HVHC",
				"TCU_OSEA_MAR_GUSH",
				"TCU_OSEA_MAR_JTTR",
				"TCU_OSEA_MAR_FCAS",
				"TCU_OSEA_MAR_BOAT",
				
				"TCU_OSEA_MAR_HVHC_BENC",
				"TCU_OSEA_MAR_HVHC_MEDI",
				"TCU_OSEA_MAR_HVHC_TRAN",
				
				"TCU_OSEA_MAR_ammobox",
				"TCU_OSEA_MAR_wbox",
				
				//TCU BELKin Panzers
				"TCU_BELK_MSL_BLU",
				"TCU_BELK_MTL_BLU",
				"TCU_BELK_MOF_BLU",
				"TCU_BELK_MRM_BLU",
				"TCU_BELK_MRMAT_BLU",
				"TCU_BELK_MMKM_BLU",
				"TCU_BELK_MSNP_BLU",
				"TCU_BELK_MMMG_BLU",
				"TCU_BELK_MMMGA_BLU",
				"TCU_BELK_MUAV_BLU",
				"TCU_BELK_MAMMO_BLU",
				"TCU_BELK_MEN_BLU",
				"TCU_BELK_MMD_BLU",
				"TCU_BELK_MAAR_BLU",
				"TCU_BELK_MAR_BLU",
				"TCU_BELK_MAAT_BLU",
				"TCU_BELK_MAT_BLU",
				"TCU_BELK_MAAA_BLU",
				"TCU_BELK_MAA_BLU",
				"TCU_BELK_MHP_BLU",
				"TCU_BELK_MFP_BLU",
				"TCU_BELK_MAR_MTRA",
				"TCU_BELK_MAR_MLMG",
				"TCU_BELK_MAR_MGMG",
				"TCU_BELK_MAR_TRAN",
				"TCU_BELK_MAR_ARMT",
				"TCU_BELK_MAR_ARMA",
				"TCU_BELK_MAR_LTHC",
				"TCU_BELK_MAR_HVHC",
				"TCU_BELK_MAR_GUSH",
				"TCU_BELK_MAR_JTTR",
				"TCU_BELK_MAR_FCAS",
				"TCU_BELK_MAR_BOAT",
				
				"TCU_BELK_MAR_ammobox",
				"TCU_BELK_MAR_wbox",
				
				//TCU Salvicon Royal Guard
				"TCU_SALV_MSL_BLU",
				"TCU_SALV_MTL_BLU",
				"TCU_SALV_MOF_BLU",
				"TCU_SALV_MRM_BLU",
				"TCU_SALV_MRMAT_BLU",
				"TCU_SALV_MMKM_BLU",
				"TCU_SALV_MSNP_BLU",
				"TCU_SALV_MMMG_BLU",
				"TCU_SALV_MMMGA_BLU",
				"TCU_SALV_MUAV_BLU",
				"TCU_SALV_MAMMO_BLU",
				"TCU_SALV_MEN_BLU",
				"TCU_SALV_MMD_BLU",
				"TCU_SALV_MAAR_BLU",
				"TCU_SALV_MAR_BLU",
				"TCU_SALV_MAAT_BLU",
				"TCU_SALV_MAT_BLU",
				"TCU_SALV_MAAA_BLU",
				"TCU_SALV_MAA_BLU",
				"TCU_SALV_MHP_BLU",
				"TCU_SALV_MFP_BLU",
				"TCU_SALV_MAR_MTRA",
				"TCU_SALV_MAR_MLMG",
				"TCU_SALV_MAR_MGMG",
				"TCU_SALV_MAR_TRAN",
				"TCU_SALV_MAR_ARMT",
				"TCU_SALV_MAR_ARMA",
				"TCU_SALV_MAR_LTHC",
				"TCU_SALV_MAR_HVHC",
				"TCU_SALV_MAR_GUSH",
				"TCU_SALV_MAR_JTTR",
				"TCU_SALV_MAR_FCAS",
				"TCU_SALV_MAR_BOAT",
				
				"TCU_SALV_MAR_ammobox",
				"TCU_SALV_MAR_wbox",
				
				//TCU Yutobania Special Purpose Branch
				"TCU_YOTU_MSL_OPF",
				"TCU_YOTU_MTL_OPF",
				"TCU_YOTU_MOF_OPF",
				"TCU_YOTU_MRM_OPF",
				"TCU_YOTU_MRMAT_OPF",
				"TCU_YOTU_MMKM_OPF",
				"TCU_YOTU_MSNP_OPF",
				"TCU_YOTU_MMMG_OPF",
				"TCU_YOTU_MMMGA_OPF",
				"TCU_YOTU_MUAV_OPF",
				"TCU_YOTU_MAMMO_OPF",
				"TCU_YOTU_MEN_OPF",
				"TCU_YOTU_MMD_OPF",
				"TCU_YOTU_MAAR_OPF",
				"TCU_YOTU_MAR_OPF",
				"TCU_YOTU_MAAT_OPF",
				"TCU_YOTU_MAT_OPF",
				"TCU_YOTU_MAAA_OPF",
				"TCU_YOTU_MAA_OPF",
				"TCU_YOTU_MHP_OPF",
				"TCU_YOTU_MFP_OPF",
				"TCU_YOTU_MAR_MTRA",
				"TCU_YOTU_MAR_MLMG",
				"TCU_YOTU_MAR_MGMG",
				"TCU_YOTU_MAR_TRAN",
				"TCU_YOTU_MAR_ARMT",
				"TCU_YOTU_MAR_ARMA",
				"TCU_YOTU_MAR_LTHC",
				"TCU_YOTU_MAR_HVHC",
				"TCU_YOTU_MAR_GUSH",
				"TCU_YOTU_MAR_FCAS",
				"TCU_YOTU_MAR_BOAT",
				
				"TCU_YOTU_MAR_ammobox",
				"TCU_YOTU_MAR_wbox",

				//TCU TRID PMC
				"TCU_TRID_MSL_IND",
				"TCU_TRID_MTL_IND",
				"TCU_TRID_MMD_IND",
				"TCU_TRID_MEN_IND",
				"TCU_TRID_MRMAT_IND",
				"TCU_TRID_MAR_IND",
				"TCU_TRID_MTL_OW_IND",
				"TCU_TRID_MMD_OW_IND",
				"TCU_TRID_MUAV_OW_IND",
				"TCU_TRID_MMKM_OW_IND",
				"TCU_TRID_MMMG_IND",
				"TCU_TRID_MAT_OW_IND",
				"TCU_TRID_MTL_AAT_IND",
				"TCU_TRID_MMD_AAT_IND",
				"TCU_TRID_MAAT_AAT_IND",
				"TCU_TRID_MAT_IND",
				"TCU_TRID_MAAA_IND",
				"TCU_TRID_MAA_IND",
				"TCU_TRID_MTL_LT_IND",
				"TCU_TRID_MMD_LT_IND",
				"TCU_TRID_MEN_LT_IND",
				"TCU_TRID_MHP_IND",
				"TCU_TRID_MFP_IND",
				"TCU_TRID_MOF_CMD_IND",
				"TCU_TRID_MTL_CMD_IND",
				"TCU_TRID_MEN_CMD_IND",
				"TCU_TRID_MMD_CMD_IND",
				"TCU_TRID_MUAV_CMD_IND",
				"TCU_TRID_MPP_CMD_IND",
				"TCU_TRID_MPB_CMD_IND",
				"TCU_TRID_MRM_IND",
				"TCU_TRID_MRMB_IND",
				"TCU_TRID_G_MTL_IND",
				"TCU_TRID_G_MRMAT_IND",
				"TCU_TRID_G_MMKM_IND",
				"TCU_TRID_G_MEN_IND",
				"TCU_TRID_G_MMD_IND",
				"TCU_TRID_G_MAR_IND",
				
				"TCU_TRID_MAR_MTRA",
				"TCU_TRID_MAR_MLMG",
				"TCU_TRID_MAR_MGMG",
				"TCU_TRID_MAR_TRAN",
				"TCU_TRID_MAR_ARMT",
				"TCU_TRID_MAR_ARMA",
				"TCU_TRID_MAR_LTHC",
				"TCU_TRID_MAR_HVHC",
				"TCU_TRID_MAR_GUSH",
				"TCU_TRID_MAR_JTTR",
				"TCU_TRID_MAR_FCAS",
				"TCU_TRID_MAR_BOAT",
				
				"TCU_TRID_MAR_ammobox",
				"TCU_TRID_MAR_wbox"
        	};
        weapons[] =
        	{

        	};
        requiredVersion = 0.1;
        requiredAddons[] = {a3_characters_F};
    };
};